version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.${START_MODE}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.${START_MODE}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=${MONGODB_URI}

  db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    restart: unless-stopped

volumes:
  db-data:
